routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
//    if (config('auth.users.registration')) {
//        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
//        Route::post('register', 'RegisterController@register');
//    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');

    // Страницы
    Route::group(['prefix' => 'pages'], function () {
        Route::get('/', 'PageController@index')->name('pages.index');
        Route::get('/getTableData', 'PageController@getTableData')->name('pages.getTableData');
        Route::get('create', 'PageController@create')->name('pages.create');
        Route::post('/', 'PageController@store')->name('pages.store');
        Route::get('edit/{page}/edit', 'PageController@edit')->name('pages.edit');
        Route::delete('destroy/{page}', 'PageController@destroy')->name('pages.destroy');
        Route::put('update/{page}', 'PageController@update')->name('pages.update');
        Route::post('active', 'PageController@active')->name('pages.active');
    });

    // Заявки
    Route::group(['prefix' => 'feedback'], function () {
        Route::get('/', 'FeedbackController@index')->name('feedback.index');
        Route::get('/getTableData', 'FeedbackController@getTableData')->name('feedback.getTableData');
        Route::delete('destroy/{feedback}', 'FeedbackController@destroy')->name('feedback.destroy');
    });

    // Типы заявок
    Route::group(['prefix' => 'feedback_type'], function () {
        Route::get('/', 'FeedbackTypeController@index')->name('feedback_type.index');
        Route::get('/getTableData', 'FeedbackTypeController@getTableData')->name('feedback_type.getTableData');
        Route::get('create', 'FeedbackTypeController@create')->name('feedback_type.create');
        Route::post('/', 'FeedbackTypeController@store')->name('feedback_type.store');
        Route::get('edit/{feedback_type}/edit', 'FeedbackTypeController@edit')->name('feedback_type.edit');
        Route::delete('destroy/{feedback_type}', 'FeedbackTypeController@destroy')->name('feedback_type.destroy');
        Route::put('update/{feedback_type}', 'FeedbackTypeController@update')->name('feedback_type.update');
        Route::post('active', 'FeedbackTypeController@active')->name('feedback_type.active');
    });

    // Вакансии
    Route::group(['prefix' => 'vacancies'], function () {
        Route::get('/', 'VacancyController@index')->name('vacancies.index');
        Route::get('/getTableData', 'VacancyController@getTableData')->name('vacancies.getTableData');
        Route::get('create', 'VacancyController@create')->name('vacancies.create');
        Route::post('/', 'VacancyController@store')->name('vacancies.store');
    });

    // Блог
    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'BlogController@index')->name('blog.index');
        Route::get('/getTableData', 'BlogController@getTableData')->name('blog.getTableData');
        Route::get('create', 'BlogController@create')->name('blog.create');
        Route::post('/', 'BlogController@store')->name('blog.store');
        Route::get('edit/{page}/edit', 'BlogController@edit')->name('blog.edit');
        Route::delete('destroy/{page}', 'BlogController@destroy')->name('blog.destroy');
        Route::put('update/{page}', 'BlogController@update')->name('blog.update');
        Route::post('active', 'BlogController@active')->name('blog.active');

        Route::post('/upload', 'BlogController@upload')->name('blog.upload');
    });
});


Route::get('/', 'HomeController@index');



// Заявки / Обратная связь
Route::get('/zayavka', 'FeedbackResource@request')->name('feedback.request');
Route::resource('/feedback', 'FeedbackResource');
Route::resource('/obratnaya-svyaz', 'FeedbackResource', [
    'names' => ['index' => 'feedback.index',]
]);

// Вакансии
Route::get('/vakansii/json', function () {
    return \App\Models\Vacancy\Vacancy::where('active', 1)->paginate(5);
});
Route::resource('/vakansii', 'VacancyResource', [
    'names' => ['index' => 'vacancy.index', 'show' => 'vacancy.show']
]);

// Блог
Route::get('/zhivem', 'BlogController@index')->name('blog.index');
Route::get('/zhivem/json', function () {
    return Blog::with('media')->where('active', 1)->paginate(5);
});
Route::get('/zhivem/{alias}', 'BlogController@show')->name('blog.show');

// Страницы
Route::get('/{alias}', 'PageController@show')->name('page');


/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});

app/Models/Blog/Blog.php
<?php

namespace App\Models\Blog;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Jenssegers\Date\Date;

class Blog extends Model implements HasMediaConversions
{
    use HasMediaTrait;

    protected $table = 'blog';

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
            ->width(370)
            ->height(275)
            ->nonQueued();
    }

    public function getCreatedAtAttribute($value)
    {
        Date::setLocale('ru');
        return Date::parse($value)->format('j F Y H:i');
    }
}

resources/views/blog/index.blade.php
@extends('layouts.default')

@section('body_class', 'blog')

@section('title', 'Lorem')

@section('content')

{{-- TODO: Весь текст вынести в языковой файл --}}

    <section id="posts">
        <div class="row">
            <h1 class="text-center">Lorem</h1>
            <br>
            @if( ! empty($posts))
                @foreach($posts as $post)
                    <div class="post">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="name">
                                <h2>
                                    <a href="{{ route('blog.show', $post->alias) }}" class="">{{ $post->name }}</a>
                                </h2>
                            </div>
                            <div class="">
                                <img class="img-responsive center-block" src="{{ $post->media[0]->getURL() }}">
                                <div class="description">
                                    <p class="datetime">{{ $post->created_at }}</p>
                                    {{ $post->description }}
                                </div>
                            </div>
                            <div class="details col-sm-6 row pull-left">
                                <p>
                                    <a href="{{ route('blog.show', $post->alias) }}" class="">подробнее
                                        <i aria-hidden="true" class="fa fa-long-arrow-right"></i>
                                    </a>
                                </p>
                            </div>
                            <div class="col-sm-6 row pull-right">
                                <div class="ya-share2 text-right"
                                    data-services="vkontakte,facebook,twitter,whatsapp"
                                    data-url="{{ route('blog.show', $post->alias) }}"
                                    data-title="{{ $post->name }}"
                                    data-description="{{ $post->description }}"
                                    data-image="{{ url('/') . $post->media[0]->getURL() }}">
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
                @if($posts->lastPage() > 1)
                    <br />
                    <p class="text-center">
                        <button id="next"
                                class="button-default btn-loader center-block"
                                data-default-title="Загрузить еще"
                                data-load-title="Загрузка..."
                                data-next-post-url="{{ url('/') }}/zhivem/json?page={{ $posts->currentPage() + 1 }}">
                            <span class="btn-title">Загрузить еще</span>
                            <span class="btn-preload loader">&nbsp;&nbsp;
                                <i class="fa fa-circle-o-notch fa-spin"></i>
                            </span>
                        </button>
                        <br />
                    </p>
                @endif
            @else
                <p>ddd</p>
            @endif
        </div>
    </section>
@endsection


@section('scripts')
    @parent
    <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
    <script src="//yastatic.net/share2/share.js"></script>
    <script id="postTemplate" type="text/template">
        @{{#data}}
        <div class="col-md-12 col-sm-12 col-xs-12 post animated bounceInDown">
            <h3 class="title">@{{ name }}</h3>
            <a href="/zhivem/@{{ alias }}">
                <img class="img-responsive center-block" src="@{{ image }}">
            </a>
            <div class="blog-content post-content">
                <p class="content">
                    <span class="date">
                        @{{ created_at }}
                    </span>
                    @{{ description }}
                </p>
                <div class="post-details hidden-xs">
                     <span class="more">
                         <a href="/zhivem/@{{ alias }}" class="button-success">Далее</a>
                     </span>
                    <span class="share pull-right">
                        Поделиться:
                        <a href=""><i class="fa fa-vk left-10" aria-hidden="true"></i></a>
                        <a href=""><i class="fa fa-facebook left-10" aria-hidden="true"></i></a>
                        <a href=""><i class="fa fa-twitter left-10" aria-hidden="true"></i></a>
                    </span>
                    <br>
                </div>
                <div class="visible-xs">
                    <div class="col-xs-12">
                        <div class="xs-more">
                            <a href="/zhivem/@{{ alias }}" class="button-success">Далее</a>
                        </div>
                        <div class="xs-share ">
                            Поделиться:
                            <a href=""><i class="fa fa-vk margin_left10" aria-hidden="true"></i></a>
                            <a href=""><i class="fa fa-facebook margin_left10" aria-hidden="true"></i></a>
                            <a href=""><i class="fa fa-twitter margin_left10" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @{{/data}}
    </script>

    {{ Html::script(mix('assets/js/blog/index.js')) }}
@endsection

resources/views/blog/show.blade.php
@extends('layouts.default')

@section('body_class', 'blog')

@if( ! empty($post))
    @section('title', $post->name)
@else
    @section('title', 'Lorem')
@endif

@section('content')
    <section id="post">
        <div class="row">
            @if( ! empty($post))
                <h1 class="text-center">{{ $post->name }}</h1>
                <br>
                <div class="post">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="name">
                            <h2>
                                {{ $post->name }}
                            </h2>
                        </div>
                        <div class="">
                            <img class="img-responsive center-block" src="{{ $post->media[0]->getURL() }}">
                            <div class="description">
                                <p class="datetime">{{ $post->created_at }}</p>
                                {{ $post->description }}
                            </div>
                        </div>
                        <div class="col-sm-12 row pull-right">
                            <div class="ya-share2 text-right"
                                 data-services="vkontakte,facebook,twitter,whatsapp"
                                 data-url="{{ route('blog.show', $post->alias) }}"
                                 data-title="{{ $post->name }}"
                                 data-description="{{ $post->description }}"
                                 data-image="{{ url('/') . $post->media[0]->getURL() }}">
                            </div>
                        </div>
                    </div>
                </div>
            @else
                <p>ddd</p>
            @endif
        </div>
    </section>
@endsection

@section('scripts')
    @parent
    <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
    <script src="//yastatic.net/share2/share.js"></script>
@endsection