routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
//    if (config('auth.users.registration')) {
//        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
//        Route::post('register', 'RegisterController@register');
//    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    Route::get('permissions', 'PermissionController@index')->name('permissions');
    Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');

    // Страницы
    Route::group(['prefix' => 'pages'], function () {
        Route::get('/', 'PageController@index')->name('pages.index');
        Route::get('/getTableData', 'PageController@getTableData')->name('pages.getTableData');
        Route::get('create', 'PageController@create')->name('pages.create');
        Route::post('/', 'PageController@store')->name('pages.store');
        Route::get('edit/{page}/edit', 'PageController@edit')->name('pages.edit');
        Route::delete('destroy/{page}', 'PageController@destroy')->name('pages.destroy');
        Route::put('update/{page}', 'PageController@update')->name('pages.update');
        Route::post('active', 'PageController@active')->name('pages.active');
    });

    // Заявки
    Route::group(['prefix' => 'feedback'], function () {
        Route::get('/', 'FeedbackController@index')->name('feedback.index');
        Route::get('/getTableData', 'FeedbackController@getTableData')->name('feedback.getTableData');
        Route::delete('destroy/{feedback}', 'FeedbackController@destroy')->name('feedback.destroy');
    });

    // Типы заявок
    Route::group(['prefix' => 'feedback_type'], function () {
        Route::get('/', 'FeedbackTypeController@index')->name('feedback_type.index');
        Route::get('/getTableData', 'FeedbackTypeController@getTableData')->name('feedback_type.getTableData');
        Route::get('create', 'FeedbackTypeController@create')->name('feedback_type.create');
        Route::post('/', 'FeedbackTypeController@store')->name('feedback_type.store');
        Route::get('edit/{feedback_type}/edit', 'FeedbackTypeController@edit')->name('feedback_type.edit');
        Route::delete('destroy/{feedback_type}', 'FeedbackTypeController@destroy')->name('feedback_type.destroy');
        Route::put('update/{feedback_type}', 'FeedbackTypeController@update')->name('feedback_type.update');
        Route::post('active', 'FeedbackTypeController@active')->name('feedback_type.active');
    });

    // Вакансии
    Route::group(['prefix' => 'vacancies'], function () {
        Route::get('/', 'VacancyController@index')->name('vacancies.index');
        Route::get('/getTableData', 'VacancyController@getTableData')->name('vacancies.getTableData');
        Route::get('create', 'VacancyController@create')->name('vacancies.create');
        Route::post('/', 'VacancyController@store')->name('vacancies.store');
    });

    // Блог
    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'BlogController@index')->name('blog.index');
        Route::get('/getTableData', 'BlogController@getTableData')->name('blog.getTableData');
        Route::get('create', 'BlogController@create')->name('blog.create');
        Route::post('/', 'BlogController@store')->name('blog.store');
        Route::get('edit/{page}/edit', 'BlogController@edit')->name('blog.edit');
        Route::delete('destroy/{page}', 'BlogController@destroy')->name('blog.destroy');
        Route::put('update/{page}', 'BlogController@update')->name('blog.update');
        Route::post('active', 'BlogController@active')->name('blog.active');

        Route::post('/upload', 'BlogController@upload')->name('blog.upload');
    });
});


Route::get('/', 'HomeController@index');



// Заявки / Обратная связь
Route::get('/zayavka', 'FeedbackResource@request')->name('feedback.request');
Route::resource('/feedback', 'FeedbackResource');
Route::resource('/obratnaya-svyaz', 'FeedbackResource', [
    'names' => ['index' => 'feedback.index',]
]);

// Вакансии
Route::get('/vakansii/json', function () {
    return \App\Models\Vacancy\Vacancy::where('active', 1)->paginate(5);
});
Route::resource('/vakansii', 'VacancyResource', [
    'names' => ['index' => 'vacancy.index', 'show' => 'vacancy.show']
]);

// Блог
Route::get('/zhivem', 'BlogController@index')->name('blog.index');
Route::get('/zhivem/json', function () {
    return Blog::with('media')->where('active', 1)->paginate(5);
});
Route::get('/zhivem/{alias}', 'BlogController@show')->name('blog.show');

// Страницы
Route::get('/{alias}', 'PageController@show')->name('page');


/**
 * Membership
 */
Route::group(['as' => 'protection.'], function () {
    Route::get('membership', 'MembershipController@index')->name('membership')->middleware('protection:' . config('protection.membership.product_module_number') . ',protection.membership.failed');
    Route::get('membership/access-denied', 'MembershipController@failed')->name('membership.failed');
    Route::get('membership/clear-cache/', 'MembershipController@clearValidationCache')->name('membership.clear_validation_cache');
});

app/Models/Blog/Blog.php
<?php

namespace App\Models\Blog;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Jenssegers\Date\Date;

class Blog extends Model implements HasMediaConversions
{
    use HasMediaTrait;

    protected $table = 'blog';

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
            ->width(370)
            ->height(275)
            ->nonQueued();
    }

    public function getCreatedAtAttribute($value)
    {
        Date::setLocale('ru');
        return Date::parse($value)->format('j F Y H:i');
    }
}

resources/views/admin/blog/create.blade.php
@extends('admin.layouts.admin')

@section('title', 'Новый пост')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Добавление новой страницы</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        <form id="create-post-form" action="{{ route('admin.blog.store') }}" class="form-horizontal form-label-left" enctype="multipart/form-data">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Наименование
                                    <span class="required">*</span>
                                </label>
                                <div class="col-md-8 col-sm-8 col-xs-12">
                                    <input type="text"
                                           name="name"
                                           id="name"
                                           class="form-control"
                                           value=""
                                           placeholder="Введите наименование..">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Системное имя
                                    <span class="required">*</span></label>
                                <div class="col-md-8 col-sm-8 col-xs-12">
                                    <input type="text"
                                           name="alias"
                                           id="alias"
                                           class="form-control"
                                           value=""
                                           placeholder="Введите системное имя..">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Ключевые слова для поиска</label>
                                <div class="col-md-8 col-sm-8 col-xs-12">
                                    <input type="text"
                                           name="meta_k"
                                           id="meta_k"
                                           class="form-control"
                                           value=""
                                           placeholder="Введите ключевые слова для поисковых роботов..">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Описание для поиска</label>
                                <div class="col-sm-8">
                                    <textarea name="meta_d"
                                              id="meta_d"
                                              class="form-control"
                                              rows="3"
                                              placeholder="Введите описание для поисковых роботов.."></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Изображение
                                    <span class="required">*</span>
                                </label>
                                <div class="col-sm-8 ">
                                    {{csrf_field()}}
                                    <div class="">
                                        <div id="file-area" class="file-area">
                                            <input id="fileupload"
                                                   class="box__file"
                                                   type="file"
                                                   name="media"
                                                   accept="image/gif, image/jpeg, image/png, image/jpg">
                                            <div class="file-dummy">
                                                <span class="success">
                                                Выберите или перетащите файлы сюда
                                                </span>
                                                <span class="default">
                                                    <i class="fa fa-picture-o" aria-hidden="true"></i>
                                                    Выберите или перетащите файлы сюда
                                                </span>
                                            </div>
                                        </div>
                                        <label id="fileupload-error" class="error" for="fileupload"></label>
                                        <div id="files" class="files animated">
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Описание
                                    <span class="required">*</span>
                                </label>
                                <div class="col-sm-8">
                                    <textarea name="description"
                                              id="description"
                                              class="form-control"
                                              rows="3"></textarea>
                                    <label id="description-error" class="error" for="description"></label>
                                </div>

                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Контент
                                    <span class="required">*</span>
                                </label>
                                <div class="col-sm-8">
                                    <textarea name="content"
                                              id="content"
                                              class="form-control"
                                              rows="3"></textarea>
                                    <label id="content-error" class="error" for="content"></label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Активен</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input id="switch-active"
                                           class="switch"
                                           type="checkbox"
                                           name="active"
                                           value="0"
                                           data-on-text="Да"
                                           data-off-text="Нет">
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-8 col-sm-8 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-primary" type="reset">Очистить</button>
                                    <button type="submit" id="button" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>

                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    @parent
    <script type="text/template" id="itemTemplate">
        <div class="col-md-55 item row animated ">
            <div class="thumbnail">
                <div class="image view view-first">
                    <img style="width: 100%; display: block;" src="@{{ src }}">
                    <div class="mask">
                        <p>@{{ name }}</p>
                        <div class="tools tools-bottom">
                            <a href="" class="btn-img-delete">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="caption">
                    <p><strong>@{{ name }}</strong></p>
                    <p></p>
                </div>
            </div>
        </div>
    </script>
    <script src="{{ URL::asset('libraries/ckeditor/ckeditor.js') }}"></script>
    {{ Html::script(mix('assets/admin/js/blog/create.js')) }}
@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.layouts.admin')

@section('title', 'Посты')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Список постов</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="posts-table"
                           class="table table-striped table-bordered dt-responsive nowrap"
                           cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Системное имя</th>
                            <th>Статус</th>
                            <th>Добавлено</th>
                            <th>Обнавлено</th>
                            <th>Действия</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Системное имя</th>
                            <th>Статус</th>
                            <th>Добавлено</th>
                            <th>Обнавлено</th>
                            <th>Действия</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {{-- Шаблон предупреждения об удалении страницы --}}
    <script id="destroy-post" type="text/template">
        <p>Удалить пост "@{{ name }}"?</p>
    </script>

    {{-- Шаблон статуса активности в колонках таблицы --}}
    <script id="rowActiveColumn" type="text/template">
        @{{#active}}
        <span class="label label-primary">Активный</span>
        @{{/active}}
        @{{^active}}
        <span class="label label-danger">Не активный</span>
        @{{/active}}
    </script>

    {{-- Шаблон кнопок в колонках таблицы --}}
    <script id="actionButtonsTemplate" type="text/template">
        <a class="btn btn-xs btn-info"
           target="_blank"
           href="/admin/blog/edit/@{{ id }}/edit"
           data-toggle="tooltip"
           data-placement="top"
           title="Посмотреть  |  Редактировать">
            <i class="fa fa-pencil"></i>
        </a>

        @{{#active}}
        <button class="btn btn-xs btn-danger btn-post-active"
                data-toggle="tooltip"
                data-placement="top"
                title="Не активен"
                data-active="@{{active}}"
                data-id="@{{id}}">
            <i class="fa fa-lock" aria-hidden="true"></i>
        </button>
        @{{/active}}
        @{{^active}}
        <button
                class="btn btn-xs btn-success btn-post-active"
                data-toggle="tooltip"
                data-placement="top"
                title="Активен"
                data-active="@{{active}}"
                data-id="@{{id}}">
            <i class="fa fa-unlock" aria-hidden="true"></i>
        </button>
        @{{/active}}

        <button class="btn btn-xs btn-danger btn-post-destroy"
                data-toggle="tooltip"
                data-placement="top"
                title="Удалить"
                data-id="@{{ id }}"
                data-post-name="@{{ name }}">
            <i class="fa fa-trash"></i>
        </button>
    </script>

@endsection

@section('styles')
    @parent

@endsection

@section('scripts')
    @parent
    <script src="{{ URL::asset('libraries/ckeditor/ckeditor.js') }}"></script>
    {{ Html::script(mix('assets/admin/js/blog/index.js')) }}
@endsection